//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QueryProxy.TaskManage {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DZY_GGFW_DAMPETask", Namespace="http://schemas.datacontract.org/2004/07/CommonService.Model")]
    [System.SerializableAttribute()]
    public partial class DZY_GGFW_DAMPETask : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ENDTIMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float LATITUDEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float LONGTITUDEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PLANIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string REMARKField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime STARTTIMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TASKIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VIEWTYPEField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ENDTIME {
            get {
                return this.ENDTIMEField;
            }
            set {
                if ((this.ENDTIMEField.Equals(value) != true)) {
                    this.ENDTIMEField = value;
                    this.RaisePropertyChanged("ENDTIME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float LATITUDE {
            get {
                return this.LATITUDEField;
            }
            set {
                if ((this.LATITUDEField.Equals(value) != true)) {
                    this.LATITUDEField = value;
                    this.RaisePropertyChanged("LATITUDE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float LONGTITUDE {
            get {
                return this.LONGTITUDEField;
            }
            set {
                if ((this.LONGTITUDEField.Equals(value) != true)) {
                    this.LONGTITUDEField = value;
                    this.RaisePropertyChanged("LONGTITUDE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PLANID {
            get {
                return this.PLANIDField;
            }
            set {
                if ((this.PLANIDField.Equals(value) != true)) {
                    this.PLANIDField = value;
                    this.RaisePropertyChanged("PLANID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string REMARK {
            get {
                return this.REMARKField;
            }
            set {
                if ((object.ReferenceEquals(this.REMARKField, value) != true)) {
                    this.REMARKField = value;
                    this.RaisePropertyChanged("REMARK");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime STARTTIME {
            get {
                return this.STARTTIMEField;
            }
            set {
                if ((this.STARTTIMEField.Equals(value) != true)) {
                    this.STARTTIMEField = value;
                    this.RaisePropertyChanged("STARTTIME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TASKID {
            get {
                return this.TASKIDField;
            }
            set {
                if ((object.ReferenceEquals(this.TASKIDField, value) != true)) {
                    this.TASKIDField = value;
                    this.RaisePropertyChanged("TASKID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VIEWTYPE {
            get {
                return this.VIEWTYPEField;
            }
            set {
                if ((object.ReferenceEquals(this.VIEWTYPEField, value) != true)) {
                    this.VIEWTYPEField = value;
                    this.RaisePropertyChanged("VIEWTYPE");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.artech.com", ConfigurationName="TaskManage.TaskManage")]
    public interface TaskManage {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.artech.com/TaskManage/insertOrUpdateTask", ReplyAction="http://www.artech.com/TaskManage/insertOrUpdateTaskResponse")]
        void insertOrUpdateTask(QueryProxy.TaskManage.DZY_GGFW_DAMPETask task);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.artech.com/TaskManage/deleteTask", ReplyAction="http://www.artech.com/TaskManage/deleteTaskResponse")]
        void deleteTask(QueryProxy.TaskManage.DZY_GGFW_DAMPETask task);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.artech.com/TaskManage/queryTask", ReplyAction="http://www.artech.com/TaskManage/queryTaskResponse")]
        QueryProxy.TaskManage.DZY_GGFW_DAMPETask queryTask(string taskid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.artech.com/TaskManage/queryTasks", ReplyAction="http://www.artech.com/TaskManage/queryTasksResponse")]
        System.Collections.Generic.List<QueryProxy.TaskManage.DZY_GGFW_DAMPETask> queryTasks(System.DateTime starttime, System.DateTime endtime);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TaskManageChannel : QueryProxy.TaskManage.TaskManage, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TaskManageClient : System.ServiceModel.ClientBase<QueryProxy.TaskManage.TaskManage>, QueryProxy.TaskManage.TaskManage {
        
        public TaskManageClient() {
        }
        
        public TaskManageClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TaskManageClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TaskManageClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TaskManageClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void insertOrUpdateTask(QueryProxy.TaskManage.DZY_GGFW_DAMPETask task) {
            base.Channel.insertOrUpdateTask(task);
        }
        
        public void deleteTask(QueryProxy.TaskManage.DZY_GGFW_DAMPETask task) {
            base.Channel.deleteTask(task);
        }
        
        public QueryProxy.TaskManage.DZY_GGFW_DAMPETask queryTask(string taskid) {
            return base.Channel.queryTask(taskid);
        }
        
        public System.Collections.Generic.List<QueryProxy.TaskManage.DZY_GGFW_DAMPETask> queryTasks(System.DateTime starttime, System.DateTime endtime) {
            return base.Channel.queryTasks(starttime, endtime);
        }
    }
}
