//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QueryProxy.ParaConfiguration {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DZY_GGFW_DAMPECSPZ", Namespace="http://schemas.datacontract.org/2004/07/CommonService.Model")]
    [System.SerializableAttribute()]
    public partial class DZY_GGFW_DAMPECSPZ : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CSCDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CSDHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CSMCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CSWZField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CSZField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RWLBField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SSDJField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SSFZField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XHField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CSCD {
            get {
                return this.CSCDField;
            }
            set {
                if ((object.ReferenceEquals(this.CSCDField, value) != true)) {
                    this.CSCDField = value;
                    this.RaisePropertyChanged("CSCD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CSDH {
            get {
                return this.CSDHField;
            }
            set {
                if ((object.ReferenceEquals(this.CSDHField, value) != true)) {
                    this.CSDHField = value;
                    this.RaisePropertyChanged("CSDH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CSMC {
            get {
                return this.CSMCField;
            }
            set {
                if ((object.ReferenceEquals(this.CSMCField, value) != true)) {
                    this.CSMCField = value;
                    this.RaisePropertyChanged("CSMC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CSWZ {
            get {
                return this.CSWZField;
            }
            set {
                if ((object.ReferenceEquals(this.CSWZField, value) != true)) {
                    this.CSWZField = value;
                    this.RaisePropertyChanged("CSWZ");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CSZ {
            get {
                return this.CSZField;
            }
            set {
                if ((object.ReferenceEquals(this.CSZField, value) != true)) {
                    this.CSZField = value;
                    this.RaisePropertyChanged("CSZ");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RWLB {
            get {
                return this.RWLBField;
            }
            set {
                if ((object.ReferenceEquals(this.RWLBField, value) != true)) {
                    this.RWLBField = value;
                    this.RaisePropertyChanged("RWLB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SSDJ {
            get {
                return this.SSDJField;
            }
            set {
                if ((object.ReferenceEquals(this.SSDJField, value) != true)) {
                    this.SSDJField = value;
                    this.RaisePropertyChanged("SSDJ");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SSFZ {
            get {
                return this.SSFZField;
            }
            set {
                if ((object.ReferenceEquals(this.SSFZField, value) != true)) {
                    this.SSFZField = value;
                    this.RaisePropertyChanged("SSFZ");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XH {
            get {
                return this.XHField;
            }
            set {
                if ((object.ReferenceEquals(this.XHField, value) != true)) {
                    this.XHField = value;
                    this.RaisePropertyChanged("XH");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ParaConfiguration.ParaConfiguration")]
    public interface ParaConfiguration {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ParaConfiguration/insertOrUpdate", ReplyAction="http://tempuri.org/ParaConfiguration/insertOrUpdateResponse")]
        void insertOrUpdate(QueryProxy.ParaConfiguration.DZY_GGFW_DAMPECSPZ paraConfig);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ParaConfiguration/queryAllConfig", ReplyAction="http://tempuri.org/ParaConfiguration/queryAllConfigResponse")]
        QueryProxy.ParaConfiguration.DZY_GGFW_DAMPECSPZ[] queryAllConfig();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ParaConfigurationChannel : QueryProxy.ParaConfiguration.ParaConfiguration, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ParaConfigurationClient : System.ServiceModel.ClientBase<QueryProxy.ParaConfiguration.ParaConfiguration>, QueryProxy.ParaConfiguration.ParaConfiguration {
        
        public ParaConfigurationClient() {
        }
        
        public ParaConfigurationClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ParaConfigurationClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ParaConfigurationClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ParaConfigurationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void insertOrUpdate(QueryProxy.ParaConfiguration.DZY_GGFW_DAMPECSPZ paraConfig) {
            base.Channel.insertOrUpdate(paraConfig);
        }
        
        public QueryProxy.ParaConfiguration.DZY_GGFW_DAMPECSPZ[] queryAllConfig() {
            return base.Channel.queryAllConfig();
        }
    }
}
